// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilbhewyiqqgliivqyvjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsYmhld3lpcXFnbGlpdnF5dmpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NzYzNTgsImV4cCI6MjA2NTI1MjM1OH0.Tvksb8btisILZuY0irkFBF9SQ3lKawYIX-vaZKJCJBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);